# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tourism.simulator.v1 import simulator_pb2 as tourism_dot_simulator_dot_v1_dot_simulator__pb2


class SimulatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdatePosition = channel.unary_unary(
                '/tourism.simulator.v1.SimulatorService/UpdatePosition',
                request_serializer=tourism_dot_simulator_dot_v1_dot_simulator__pb2.UpdatePositionRequest.SerializeToString,
                response_deserializer=tourism_dot_simulator_dot_v1_dot_simulator__pb2.Position.FromString,
                _registered_method=True)
        self.GetPosition = channel.unary_unary(
                '/tourism.simulator.v1.SimulatorService/GetPosition',
                request_serializer=tourism_dot_simulator_dot_v1_dot_simulator__pb2.GetPositionRequest.SerializeToString,
                response_deserializer=tourism_dot_simulator_dot_v1_dot_simulator__pb2.Position.FromString,
                _registered_method=True)


class SimulatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdatePosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdatePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePosition,
                    request_deserializer=tourism_dot_simulator_dot_v1_dot_simulator__pb2.UpdatePositionRequest.FromString,
                    response_serializer=tourism_dot_simulator_dot_v1_dot_simulator__pb2.Position.SerializeToString,
            ),
            'GetPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPosition,
                    request_deserializer=tourism_dot_simulator_dot_v1_dot_simulator__pb2.GetPositionRequest.FromString,
                    response_serializer=tourism_dot_simulator_dot_v1_dot_simulator__pb2.Position.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tourism.simulator.v1.SimulatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tourism.simulator.v1.SimulatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimulatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdatePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.simulator.v1.SimulatorService/UpdatePosition',
            tourism_dot_simulator_dot_v1_dot_simulator__pb2.UpdatePositionRequest.SerializeToString,
            tourism_dot_simulator_dot_v1_dot_simulator__pb2.Position.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.simulator.v1.SimulatorService/GetPosition',
            tourism_dot_simulator_dot_v1_dot_simulator__pb2.GetPositionRequest.SerializeToString,
            tourism_dot_simulator_dot_v1_dot_simulator__pb2.Position.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
