# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tourism/simulator/v1/simulator.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'tourism/simulator/v1/simulator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$tourism/simulator/v1/simulator.proto\x12\x14tourism.simulator.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"|\n\x08Position\x12\x17\n\x07user_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n\x08latitude\x18\x02 \x01(\x01R\x08latitude\x12\x1c\n\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1d\n\nupdated_at\x18\x04 \x01(\tR\tupdatedAt\"Q\n\x15UpdatePositionRequest\x12\x1a\n\x08latitude\x18\x01 \x01(\x01R\x08latitude\x12\x1c\n\tlongitude\x18\x02 \x01(\x01R\tlongitude\"\x14\n\x12GetPositionRequest2\x96\x02\n\x10SimulatorService\x12\x84\x01\n\x0eUpdatePosition\x12+.tourism.simulator.v1.UpdatePositionRequest\x1a\x1e.tourism.simulator.v1.Position\"%\x82\xd3\xe4\x93\x02\x1f\x1a\x1a/api/v1/simulator/position:\x01*\x12{\n\x0bGetPosition\x12(.tourism.simulator.v1.GetPositionRequest\x1a\x1e.tourism.simulator.v1.Position\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/simulator/positionB\xea\x01\n\x14tourism.simulator.v1P\x01ZPgithub.com/pyroaktiv/soa-tourism/gateway/gen/go/tourism/simulator/v1;simulatorv1\x92\x41}\x12S\n\rSimulator API\x12;Servis za belezenje i citanje trenutne GPS lokacije turiste2\x05\x30.1.0*\x02\x01\x02\x32\x10\x61pplication/json:\x10\x61pplication/jsonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tourism.simulator.v1.simulator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024tourism.simulator.v1P\001ZPgithub.com/pyroaktiv/soa-tourism/gateway/gen/go/tourism/simulator/v1;simulatorv1\222A}\022S\n\rSimulator API\022;Servis za belezenje i citanje trenutne GPS lokacije turiste2\0050.1.0*\002\001\0022\020application/json:\020application/json'
  _globals['_SIMULATORSERVICE'].methods_by_name['UpdatePosition']._loaded_options = None
  _globals['_SIMULATORSERVICE'].methods_by_name['UpdatePosition']._serialized_options = b'\202\323\344\223\002\037\032\032/api/v1/simulator/position:\001*'
  _globals['_SIMULATORSERVICE'].methods_by_name['GetPosition']._loaded_options = None
  _globals['_SIMULATORSERVICE'].methods_by_name['GetPosition']._serialized_options = b'\202\323\344\223\002\034\022\032/api/v1/simulator/position'
  _globals['_POSITION']._serialized_start=140
  _globals['_POSITION']._serialized_end=264
  _globals['_UPDATEPOSITIONREQUEST']._serialized_start=266
  _globals['_UPDATEPOSITIONREQUEST']._serialized_end=347
  _globals['_GETPOSITIONREQUEST']._serialized_start=349
  _globals['_GETPOSITIONREQUEST']._serialized_end=369
  _globals['_SIMULATORSERVICE']._serialized_start=372
  _globals['_SIMULATORSERVICE']._serialized_end=650
# @@protoc_insertion_point(module_scope)
