# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from tourism.auth.v1 import auth_pb2 as tourism_dot_auth_dot_v1_dot_auth__pb2


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/tourism.auth.v1.AuthService/Register',
                request_serializer=tourism_dot_auth_dot_v1_dot_auth__pb2.RegisterRequest.SerializeToString,
                response_deserializer=tourism_dot_auth_dot_v1_dot_auth__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/tourism.auth.v1.AuthService/Login',
                request_serializer=tourism_dot_auth_dot_v1_dot_auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=tourism_dot_auth_dot_v1_dot_auth__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.Refresh = channel.unary_unary(
                '/tourism.auth.v1.AuthService/Refresh',
                request_serializer=tourism_dot_auth_dot_v1_dot_auth__pb2.RefreshRequest.SerializeToString,
                response_deserializer=tourism_dot_auth_dot_v1_dot_auth__pb2.TokenPair.FromString,
                _registered_method=True)
        self.Validate = channel.unary_unary(
                '/tourism.auth.v1.AuthService/Validate',
                request_serializer=tourism_dot_auth_dot_v1_dot_auth__pb2.ValidateRequest.SerializeToString,
                response_deserializer=tourism_dot_auth_dot_v1_dot_auth__pb2.ValidateResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/tourism.auth.v1.AuthService/Logout',
                request_serializer=tourism_dot_auth_dot_v1_dot_auth__pb2.LogoutRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Register creates a new user account and returns a token pair.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Login authenticates with username or email + password and returns a token pair.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Refresh(self, request, context):
        """Refresh rotates a refresh token and returns a new token pair.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Validate(self, request, context):
        """Validate verifies an access token and returns the associated user.
        Called internally by other services — not exposed through the gateway.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Logout revokes the given refresh token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=tourism_dot_auth_dot_v1_dot_auth__pb2.RegisterRequest.FromString,
                    response_serializer=tourism_dot_auth_dot_v1_dot_auth__pb2.AuthResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=tourism_dot_auth_dot_v1_dot_auth__pb2.LoginRequest.FromString,
                    response_serializer=tourism_dot_auth_dot_v1_dot_auth__pb2.AuthResponse.SerializeToString,
            ),
            'Refresh': grpc.unary_unary_rpc_method_handler(
                    servicer.Refresh,
                    request_deserializer=tourism_dot_auth_dot_v1_dot_auth__pb2.RefreshRequest.FromString,
                    response_serializer=tourism_dot_auth_dot_v1_dot_auth__pb2.TokenPair.SerializeToString,
            ),
            'Validate': grpc.unary_unary_rpc_method_handler(
                    servicer.Validate,
                    request_deserializer=tourism_dot_auth_dot_v1_dot_auth__pb2.ValidateRequest.FromString,
                    response_serializer=tourism_dot_auth_dot_v1_dot_auth__pb2.ValidateResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=tourism_dot_auth_dot_v1_dot_auth__pb2.LogoutRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tourism.auth.v1.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tourism.auth.v1.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.auth.v1.AuthService/Register',
            tourism_dot_auth_dot_v1_dot_auth__pb2.RegisterRequest.SerializeToString,
            tourism_dot_auth_dot_v1_dot_auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.auth.v1.AuthService/Login',
            tourism_dot_auth_dot_v1_dot_auth__pb2.LoginRequest.SerializeToString,
            tourism_dot_auth_dot_v1_dot_auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Refresh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.auth.v1.AuthService/Refresh',
            tourism_dot_auth_dot_v1_dot_auth__pb2.RefreshRequest.SerializeToString,
            tourism_dot_auth_dot_v1_dot_auth__pb2.TokenPair.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.auth.v1.AuthService/Validate',
            tourism_dot_auth_dot_v1_dot_auth__pb2.ValidateRequest.SerializeToString,
            tourism_dot_auth_dot_v1_dot_auth__pb2.ValidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.auth.v1.AuthService/Logout',
            tourism_dot_auth_dot_v1_dot_auth__pb2.LogoutRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
