// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               unknown
// source: tourism/tour/v1/tour.proto

/* eslint-disable */

export const protobufPackage = "tourism.tour.v1";

export enum TourStatus {
  TOUR_STATUS_UNSPECIFIED = 0,
  TOUR_STATUS_DRAFT = 1,
  TOUR_STATUS_PUBLISHED = 2,
  TOUR_STATUS_ARCHIVE_PENDING = 3,
  TOUR_STATUS_ARCHIVED = 4,
  UNRECOGNIZED = -1,
}

export enum TransportType {
  TRANSPORT_TYPE_UNSPECIFIED = 0,
  TRANSPORT_TYPE_FOOT = 1,
  TRANSPORT_TYPE_BICYCLE = 2,
  TRANSPORT_TYPE_CAR = 3,
  UNRECOGNIZED = -1,
}

export interface Keypoint {
  name: string;
  description: string;
  latitude: number;
  longitude: number;
  order: number;
  imageUrl: string;
}

export interface TransportTime {
  transport: TransportType;
  minutes: number;
}

export interface Review {
  id: string;
  touristId: string;
  touristUsername: string;
  rating: number;
  comment: string;
  visitDate: string;
  createdAt: string;
  imageUrls: string[];
}

export interface Tour {
  id: string;
  authorId: string;
  name: string;
  description: string;
  difficulty: number;
  tags: string[];
  status: TourStatus;
  price: number;
  lengthKm: number;
  publishedAt: string;
  archivedAt: string;
  createdAt: string;
  keypoints: Keypoint[];
  transportTimes: TransportTime[];
  reviews: Review[];
}

export interface CreateTourRequest {
  name: string;
  description: string;
  difficulty: number;
  tags: string[];
}

export interface UpdateTourRequest {
  id: string;
  name?: string | undefined;
  description?: string | undefined;
  difficulty?: number | undefined;
  tags: string[];
  price?: number | undefined;
}

export interface GetTourRequest {
  id: string;
}

export interface ListMyToursRequest {
}

export interface ListPublishedToursRequest {
}

export interface ListToursResponse {
  tours: Tour[];
}

export interface AddKeypointRequest {
  tourId: string;
  name: string;
  description: string;
  latitude: number;
  longitude: number;
  imageUrl: string;
}

export interface AddTransportTimeRequest {
  tourId: string;
  transport: TransportType;
  minutes: number;
}

export interface PublishTourRequest {
  id: string;
}

export interface ArchiveTourRequest {
  id: string;
}

export interface ReactivateTourRequest {
  id: string;
}

export interface AddReviewRequest {
  tourId: string;
  rating: number;
  comment: string;
  visitDate: string;
  imageUrls: string[];
}

export interface UploadReviewImageRequest {
  imageData: Uint8Array;
  contentType: string;
}

export interface UploadReviewImageResponse {
  imageUrl: string;
}

export interface UploadKeypointImageRequest {
  imageData: Uint8Array;
  contentType: string;
}

export interface UploadKeypointImageResponse {
  imageUrl: string;
}

export interface UpdateKeypointRequest {
  tourId: string;
  order: number;
  name: string;
  description: string;
  latitude: number;
  longitude: number;
  imageUrl: string;
}

export interface DeleteKeypointRequest {
  tourId: string;
  order: number;
}
