// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               unknown
// source: tourism/auth/v1/auth.proto

/* eslint-disable */

export const protobufPackage = "tourism.auth.v1";

export interface User {
  id: string;
  username: string;
  email: string;
  roles: string[];
  state: string;
}

export interface TokenPair {
  accessToken: string;
  accessTokenExpiresAt: string;
  refreshToken: string;
  refreshTokenExpiresAt: string;
}

export interface AuthResponse {
  user: User | undefined;
  tokens: TokenPair | undefined;
}

export interface RegisterRequest {
  username: string;
  email: string;
  password: string;
  /** roles defaults to ["user"] when empty. */
  roles: string[];
}

export interface LoginRequest {
  /** identifier accepts either a username or email address. */
  identifier: string;
  password: string;
}

export interface RefreshRequest {
  refreshToken: string;
}

export interface ValidateRequest {
  accessToken: string;
}

export interface ValidateResponse {
  valid: boolean;
  /** user is populated only when valid is true. */
  user: User | undefined;
}

export interface LogoutRequest {
  refreshToken: string;
}

export interface ListUsersRequest {
  pageSize: number;
  /** Simple offset-based pagination */
  pageNumber: number;
}

export interface ListUsersResponse {
  users: User[];
  totalCount: string;
}

export interface SearchUsersRequest {
  username: string;
}

export interface SearchUsersResponse {
  users: User[];
}

export interface BlockUserRequest {
  userId: string;
}

export interface BlockUserResponse {
  success: boolean;
}

export interface GetUsernameRequest {
  userId: string;
}

export interface GetUsernameResponse {
  username: string;
}
