// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               unknown
// source: tourism/follower/v1/follower.proto

/* eslint-disable */

export const protobufPackage = "tourism.follower.v1";

export interface FollowRequest {
  /** The user to follow. The follower is the authenticated caller. */
  followeeId: string;
}

export interface FollowResponse {
  success: boolean;
}

export interface UnfollowRequest {
  /** The user to unfollow. The follower is the authenticated caller. */
  followeeId: string;
}

export interface UnfollowResponse {
  success: boolean;
}

export interface GetFollowersRequest {
  userId: string;
  limit: number;
  offset: number;
}

export interface GetFollowersResponse {
  userIds: string[];
  total: number;
}

export interface GetFollowingRequest {
  userId: string;
  limit: number;
  offset: number;
}

export interface GetFollowingResponse {
  userIds: string[];
  total: number;
}

export interface IsFollowingRequest {
  followerId: string;
  followeeId: string;
}

export interface IsFollowingResponse {
  isFollowing: boolean;
}

export interface GetFollowedUserIdsRequest {
  userId: string;
}

export interface GetFollowedUserIdsResponse {
  userIds: string[];
}

export interface GetRecommendationsRequest {
  /** Maximum number of recommendations to return. Defaults to 10 if 0. */
  limit: number;
}

export interface Recommendation {
  userId: string;
  mutualFollows: number;
  username: string;
}

export interface GetRecommendationsResponse {
  recommendations: Recommendation[];
}
