# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tourism.stakeholders.v1 import stakeholders_pb2 as tourism_dot_stakeholders_dot_v1_dot_stakeholders__pb2


class StakeholderServiceStub(object):
    """StakeholderService manages user profiles.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProfile = channel.unary_unary(
                '/tourism.stakeholders.v1.StakeholderService/GetProfile',
                request_serializer=tourism_dot_stakeholders_dot_v1_dot_stakeholders__pb2.GetProfileRequest.SerializeToString,
                response_deserializer=tourism_dot_stakeholders_dot_v1_dot_stakeholders__pb2.Profile.FromString,
                _registered_method=True)
        self.UpdateProfile = channel.unary_unary(
                '/tourism.stakeholders.v1.StakeholderService/UpdateProfile',
                request_serializer=tourism_dot_stakeholders_dot_v1_dot_stakeholders__pb2.UpdateProfileRequest.SerializeToString,
                response_deserializer=tourism_dot_stakeholders_dot_v1_dot_stakeholders__pb2.Profile.FromString,
                _registered_method=True)
        self.DeleteProfilePhoto = channel.unary_unary(
                '/tourism.stakeholders.v1.StakeholderService/DeleteProfilePhoto',
                request_serializer=tourism_dot_stakeholders_dot_v1_dot_stakeholders__pb2.DeleteProfilePhotoRequest.SerializeToString,
                response_deserializer=tourism_dot_stakeholders_dot_v1_dot_stakeholders__pb2.Profile.FromString,
                _registered_method=True)


class StakeholderServiceServicer(object):
    """StakeholderService manages user profiles.
    """

    def GetProfile(self, request, context):
        """GetProfile returns the profile for the given user. Public — no token required.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProfile(self, request, context):
        """UpdateProfile creates or updates the authenticated user's profile.
        Requires Authorization: Bearer <access_token>.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProfilePhoto(self, request, context):
        """DeleteProfilePhoto removes the profile photo from storage and clears the URL.
        Requires Authorization: Bearer <access_token>.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StakeholderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfile,
                    request_deserializer=tourism_dot_stakeholders_dot_v1_dot_stakeholders__pb2.GetProfileRequest.FromString,
                    response_serializer=tourism_dot_stakeholders_dot_v1_dot_stakeholders__pb2.Profile.SerializeToString,
            ),
            'UpdateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProfile,
                    request_deserializer=tourism_dot_stakeholders_dot_v1_dot_stakeholders__pb2.UpdateProfileRequest.FromString,
                    response_serializer=tourism_dot_stakeholders_dot_v1_dot_stakeholders__pb2.Profile.SerializeToString,
            ),
            'DeleteProfilePhoto': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProfilePhoto,
                    request_deserializer=tourism_dot_stakeholders_dot_v1_dot_stakeholders__pb2.DeleteProfilePhotoRequest.FromString,
                    response_serializer=tourism_dot_stakeholders_dot_v1_dot_stakeholders__pb2.Profile.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tourism.stakeholders.v1.StakeholderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tourism.stakeholders.v1.StakeholderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StakeholderService(object):
    """StakeholderService manages user profiles.
    """

    @staticmethod
    def GetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.stakeholders.v1.StakeholderService/GetProfile',
            tourism_dot_stakeholders_dot_v1_dot_stakeholders__pb2.GetProfileRequest.SerializeToString,
            tourism_dot_stakeholders_dot_v1_dot_stakeholders__pb2.Profile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.stakeholders.v1.StakeholderService/UpdateProfile',
            tourism_dot_stakeholders_dot_v1_dot_stakeholders__pb2.UpdateProfileRequest.SerializeToString,
            tourism_dot_stakeholders_dot_v1_dot_stakeholders__pb2.Profile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProfilePhoto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.stakeholders.v1.StakeholderService/DeleteProfilePhoto',
            tourism_dot_stakeholders_dot_v1_dot_stakeholders__pb2.DeleteProfilePhotoRequest.SerializeToString,
            tourism_dot_stakeholders_dot_v1_dot_stakeholders__pb2.Profile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
