// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               unknown
// source: tourism/saga/v1/saga.proto

/* eslint-disable */

export const protobufPackage = "tourism.saga.v1";

/** Status koji označava da li se operacije potvrđuju (Commit) ili poništavaju (Rollback) */
export enum SagaStatus {
  SAGA_STATUS_UNSPECIFIED = 0,
  SAGA_STATUS_SUCCESS = 1,
  SAGA_STATUS_ROLLBACK = 2,
  UNRECOGNIZED = -1,
}

/** 1. Auth -> Orchestrator: Započinjanje sage */
export interface StartBlockAuthorEvent {
  /** Ovo služi i kao ID sage */
  userId: string;
}

/** 2. Orchestrator -> Tour: Komanda za arhiviranje tura */
export interface ArchiveToursCommand {
  userId: string;
}

/** 3. Tour -> Orchestrator: Rezultat arhiviranja tura */
export interface ArchiveToursResultEvent {
  userId: string;
  success: boolean;
  /** Popunjeno samo ako je success = true */
  tourIds: string[];
  /** Opciono, zbog logovanja */
  errorMessage: string;
}

/** 4. Orchestrator -> Payment: Komanda za izbacivanje iz korpi */
export interface RemoveToursFromCartCommand {
  userId: string;
  tourIds: string[];
}

/** 5. Payment -> Orchestrator: Rezultat izbacivanja iz korpi */
export interface RemoveToursFromCartResultEvent {
  userId: string;
  success: boolean;
  errorMessage: string;
}

/** 6. Orchestrator -> Auth & Tour: Finalna komanda (Confirm ili Rollback) */
export interface FinalizeBlockAuthorCommand {
  userId: string;
  status: SagaStatus;
}
