# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from tourism.tour.v1 import tour_pb2 as tourism_dot_tour_dot_v1_dot_tour__pb2


class TourServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTour = channel.unary_unary(
                '/tourism.tour.v1.TourService/CreateTour',
                request_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.CreateTourRequest.SerializeToString,
                response_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.FromString,
                _registered_method=True)
        self.UpdateTour = channel.unary_unary(
                '/tourism.tour.v1.TourService/UpdateTour',
                request_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.UpdateTourRequest.SerializeToString,
                response_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.FromString,
                _registered_method=True)
        self.GetTour = channel.unary_unary(
                '/tourism.tour.v1.TourService/GetTour',
                request_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.GetTourRequest.SerializeToString,
                response_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.FromString,
                _registered_method=True)
        self.ListMyTours = channel.unary_unary(
                '/tourism.tour.v1.TourService/ListMyTours',
                request_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.ListMyToursRequest.SerializeToString,
                response_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.ListToursResponse.FromString,
                _registered_method=True)
        self.ListPublishedTours = channel.unary_unary(
                '/tourism.tour.v1.TourService/ListPublishedTours',
                request_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.ListPublishedToursRequest.SerializeToString,
                response_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.ListToursResponse.FromString,
                _registered_method=True)
        self.AddKeypoint = channel.unary_unary(
                '/tourism.tour.v1.TourService/AddKeypoint',
                request_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.AddKeypointRequest.SerializeToString,
                response_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.FromString,
                _registered_method=True)
        self.UpdateKeypoint = channel.unary_unary(
                '/tourism.tour.v1.TourService/UpdateKeypoint',
                request_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.UpdateKeypointRequest.SerializeToString,
                response_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.FromString,
                _registered_method=True)
        self.DeleteKeypoint = channel.unary_unary(
                '/tourism.tour.v1.TourService/DeleteKeypoint',
                request_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.DeleteKeypointRequest.SerializeToString,
                response_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.FromString,
                _registered_method=True)
        self.AddTransportTime = channel.unary_unary(
                '/tourism.tour.v1.TourService/AddTransportTime',
                request_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.AddTransportTimeRequest.SerializeToString,
                response_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.FromString,
                _registered_method=True)
        self.PublishTour = channel.unary_unary(
                '/tourism.tour.v1.TourService/PublishTour',
                request_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.PublishTourRequest.SerializeToString,
                response_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.FromString,
                _registered_method=True)
        self.ArchiveTour = channel.unary_unary(
                '/tourism.tour.v1.TourService/ArchiveTour',
                request_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.ArchiveTourRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ReactivateTour = channel.unary_unary(
                '/tourism.tour.v1.TourService/ReactivateTour',
                request_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.ReactivateTourRequest.SerializeToString,
                response_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.FromString,
                _registered_method=True)
        self.AddReview = channel.unary_unary(
                '/tourism.tour.v1.TourService/AddReview',
                request_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.AddReviewRequest.SerializeToString,
                response_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.FromString,
                _registered_method=True)
        self.UploadReviewImage = channel.unary_unary(
                '/tourism.tour.v1.TourService/UploadReviewImage',
                request_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.UploadReviewImageRequest.SerializeToString,
                response_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.UploadReviewImageResponse.FromString,
                _registered_method=True)
        self.UploadKeypointImage = channel.unary_unary(
                '/tourism.tour.v1.TourService/UploadKeypointImage',
                request_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.UploadKeypointImageRequest.SerializeToString,
                response_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.UploadKeypointImageResponse.FromString,
                _registered_method=True)
        self.StartExecution = channel.unary_unary(
                '/tourism.tour.v1.TourService/StartExecution',
                request_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.StartExecutionRequest.SerializeToString,
                response_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.TourExecution.FromString,
                _registered_method=True)
        self.HeartbeatExecution = channel.unary_unary(
                '/tourism.tour.v1.TourService/HeartbeatExecution',
                request_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.AbandonExecution = channel.unary_unary(
                '/tourism.tour.v1.TourService/AbandonExecution',
                request_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.AbandonExecutionRequest.SerializeToString,
                response_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.AbandonExecutionResponse.FromString,
                _registered_method=True)
        self.GetExecution = channel.unary_unary(
                '/tourism.tour.v1.TourService/GetExecution',
                request_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.GetTourRequest.SerializeToString,
                response_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.TourExecution.FromString,
                _registered_method=True)
        self.ListMyExecutions = channel.unary_unary(
                '/tourism.tour.v1.TourService/ListMyExecutions',
                request_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.ListMyToursRequest.SerializeToString,
                response_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.ListToursResponse.FromString,
                _registered_method=True)


class TourServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTour(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTour(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTour(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMyTours(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPublishedTours(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddKeypoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateKeypoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteKeypoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTransportTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishTour(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArchiveTour(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReactivateTour(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadReviewImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadKeypointImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartbeatExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbandonExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMyExecutions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TourServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTour': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTour,
                    request_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.CreateTourRequest.FromString,
                    response_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.SerializeToString,
            ),
            'UpdateTour': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTour,
                    request_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.UpdateTourRequest.FromString,
                    response_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.SerializeToString,
            ),
            'GetTour': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTour,
                    request_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.GetTourRequest.FromString,
                    response_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.SerializeToString,
            ),
            'ListMyTours': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMyTours,
                    request_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.ListMyToursRequest.FromString,
                    response_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.ListToursResponse.SerializeToString,
            ),
            'ListPublishedTours': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPublishedTours,
                    request_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.ListPublishedToursRequest.FromString,
                    response_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.ListToursResponse.SerializeToString,
            ),
            'AddKeypoint': grpc.unary_unary_rpc_method_handler(
                    servicer.AddKeypoint,
                    request_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.AddKeypointRequest.FromString,
                    response_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.SerializeToString,
            ),
            'UpdateKeypoint': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateKeypoint,
                    request_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.UpdateKeypointRequest.FromString,
                    response_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.SerializeToString,
            ),
            'DeleteKeypoint': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteKeypoint,
                    request_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.DeleteKeypointRequest.FromString,
                    response_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.SerializeToString,
            ),
            'AddTransportTime': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTransportTime,
                    request_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.AddTransportTimeRequest.FromString,
                    response_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.SerializeToString,
            ),
            'PublishTour': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishTour,
                    request_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.PublishTourRequest.FromString,
                    response_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.SerializeToString,
            ),
            'ArchiveTour': grpc.unary_unary_rpc_method_handler(
                    servicer.ArchiveTour,
                    request_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.ArchiveTourRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ReactivateTour': grpc.unary_unary_rpc_method_handler(
                    servicer.ReactivateTour,
                    request_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.ReactivateTourRequest.FromString,
                    response_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.SerializeToString,
            ),
            'AddReview': grpc.unary_unary_rpc_method_handler(
                    servicer.AddReview,
                    request_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.AddReviewRequest.FromString,
                    response_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.SerializeToString,
            ),
            'UploadReviewImage': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadReviewImage,
                    request_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.UploadReviewImageRequest.FromString,
                    response_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.UploadReviewImageResponse.SerializeToString,
            ),
            'UploadKeypointImage': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadKeypointImage,
                    request_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.UploadKeypointImageRequest.FromString,
                    response_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.UploadKeypointImageResponse.SerializeToString,
            ),
            'StartExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.StartExecution,
                    request_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.StartExecutionRequest.FromString,
                    response_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.TourExecution.SerializeToString,
            ),
            'HeartbeatExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartbeatExecution,
                    request_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.HeartbeatRequest.FromString,
                    response_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.HeartbeatResponse.SerializeToString,
            ),
            'AbandonExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.AbandonExecution,
                    request_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.AbandonExecutionRequest.FromString,
                    response_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.AbandonExecutionResponse.SerializeToString,
            ),
            'GetExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExecution,
                    request_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.GetTourRequest.FromString,
                    response_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.TourExecution.SerializeToString,
            ),
            'ListMyExecutions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMyExecutions,
                    request_deserializer=tourism_dot_tour_dot_v1_dot_tour__pb2.ListMyToursRequest.FromString,
                    response_serializer=tourism_dot_tour_dot_v1_dot_tour__pb2.ListToursResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tourism.tour.v1.TourService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tourism.tour.v1.TourService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TourService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTour(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.tour.v1.TourService/CreateTour',
            tourism_dot_tour_dot_v1_dot_tour__pb2.CreateTourRequest.SerializeToString,
            tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTour(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.tour.v1.TourService/UpdateTour',
            tourism_dot_tour_dot_v1_dot_tour__pb2.UpdateTourRequest.SerializeToString,
            tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTour(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.tour.v1.TourService/GetTour',
            tourism_dot_tour_dot_v1_dot_tour__pb2.GetTourRequest.SerializeToString,
            tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMyTours(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.tour.v1.TourService/ListMyTours',
            tourism_dot_tour_dot_v1_dot_tour__pb2.ListMyToursRequest.SerializeToString,
            tourism_dot_tour_dot_v1_dot_tour__pb2.ListToursResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPublishedTours(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.tour.v1.TourService/ListPublishedTours',
            tourism_dot_tour_dot_v1_dot_tour__pb2.ListPublishedToursRequest.SerializeToString,
            tourism_dot_tour_dot_v1_dot_tour__pb2.ListToursResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddKeypoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.tour.v1.TourService/AddKeypoint',
            tourism_dot_tour_dot_v1_dot_tour__pb2.AddKeypointRequest.SerializeToString,
            tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateKeypoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.tour.v1.TourService/UpdateKeypoint',
            tourism_dot_tour_dot_v1_dot_tour__pb2.UpdateKeypointRequest.SerializeToString,
            tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteKeypoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.tour.v1.TourService/DeleteKeypoint',
            tourism_dot_tour_dot_v1_dot_tour__pb2.DeleteKeypointRequest.SerializeToString,
            tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddTransportTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.tour.v1.TourService/AddTransportTime',
            tourism_dot_tour_dot_v1_dot_tour__pb2.AddTransportTimeRequest.SerializeToString,
            tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishTour(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.tour.v1.TourService/PublishTour',
            tourism_dot_tour_dot_v1_dot_tour__pb2.PublishTourRequest.SerializeToString,
            tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ArchiveTour(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.tour.v1.TourService/ArchiveTour',
            tourism_dot_tour_dot_v1_dot_tour__pb2.ArchiveTourRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReactivateTour(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.tour.v1.TourService/ReactivateTour',
            tourism_dot_tour_dot_v1_dot_tour__pb2.ReactivateTourRequest.SerializeToString,
            tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.tour.v1.TourService/AddReview',
            tourism_dot_tour_dot_v1_dot_tour__pb2.AddReviewRequest.SerializeToString,
            tourism_dot_tour_dot_v1_dot_tour__pb2.Tour.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadReviewImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.tour.v1.TourService/UploadReviewImage',
            tourism_dot_tour_dot_v1_dot_tour__pb2.UploadReviewImageRequest.SerializeToString,
            tourism_dot_tour_dot_v1_dot_tour__pb2.UploadReviewImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadKeypointImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.tour.v1.TourService/UploadKeypointImage',
            tourism_dot_tour_dot_v1_dot_tour__pb2.UploadKeypointImageRequest.SerializeToString,
            tourism_dot_tour_dot_v1_dot_tour__pb2.UploadKeypointImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.tour.v1.TourService/StartExecution',
            tourism_dot_tour_dot_v1_dot_tour__pb2.StartExecutionRequest.SerializeToString,
            tourism_dot_tour_dot_v1_dot_tour__pb2.TourExecution.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartbeatExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.tour.v1.TourService/HeartbeatExecution',
            tourism_dot_tour_dot_v1_dot_tour__pb2.HeartbeatRequest.SerializeToString,
            tourism_dot_tour_dot_v1_dot_tour__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbandonExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.tour.v1.TourService/AbandonExecution',
            tourism_dot_tour_dot_v1_dot_tour__pb2.AbandonExecutionRequest.SerializeToString,
            tourism_dot_tour_dot_v1_dot_tour__pb2.AbandonExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.tour.v1.TourService/GetExecution',
            tourism_dot_tour_dot_v1_dot_tour__pb2.GetTourRequest.SerializeToString,
            tourism_dot_tour_dot_v1_dot_tour__pb2.TourExecution.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMyExecutions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.tour.v1.TourService/ListMyExecutions',
            tourism_dot_tour_dot_v1_dot_tour__pb2.ListMyToursRequest.SerializeToString,
            tourism_dot_tour_dot_v1_dot_tour__pb2.ListToursResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
