version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: blog-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - soa-network

  blog-service:
    build: .
    container_name: blog-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_MONGODB_URI=mongodb://mongodb:27017/blogdb
    networks:
      - soa-network

volumes:
  mongo-data:

networks:
  soa-network:
    driver: bridge