// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               unknown
// source: tourism/simulator/v1/simulator.proto

/* eslint-disable */

export const protobufPackage = "tourism.simulator.v1";

export interface Position {
  userId: string;
  latitude: number;
  longitude: number;
  updatedAt: string;
}

export interface UpdatePositionRequest {
  latitude: number;
  longitude: number;
}

export interface GetPositionRequest {
}
