# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tourism.payment.v1 import payment_pb2 as tourism_dot_payment_dot_v1_dot_payment__pb2


class PaymentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCart = channel.unary_unary(
                '/tourism.payment.v1.PaymentService/GetCart',
                request_serializer=tourism_dot_payment_dot_v1_dot_payment__pb2.GetCartRequest.SerializeToString,
                response_deserializer=tourism_dot_payment_dot_v1_dot_payment__pb2.ShoppingCart.FromString,
                _registered_method=True)
        self.AddToCart = channel.unary_unary(
                '/tourism.payment.v1.PaymentService/AddToCart',
                request_serializer=tourism_dot_payment_dot_v1_dot_payment__pb2.AddToCartRequest.SerializeToString,
                response_deserializer=tourism_dot_payment_dot_v1_dot_payment__pb2.ShoppingCart.FromString,
                _registered_method=True)
        self.RemoveFromCart = channel.unary_unary(
                '/tourism.payment.v1.PaymentService/RemoveFromCart',
                request_serializer=tourism_dot_payment_dot_v1_dot_payment__pb2.RemoveFromCartRequest.SerializeToString,
                response_deserializer=tourism_dot_payment_dot_v1_dot_payment__pb2.ShoppingCart.FromString,
                _registered_method=True)
        self.Checkout = channel.unary_unary(
                '/tourism.payment.v1.PaymentService/Checkout',
                request_serializer=tourism_dot_payment_dot_v1_dot_payment__pb2.CheckoutRequest.SerializeToString,
                response_deserializer=tourism_dot_payment_dot_v1_dot_payment__pb2.CheckoutResponse.FromString,
                _registered_method=True)
        self.ListMyTokens = channel.unary_unary(
                '/tourism.payment.v1.PaymentService/ListMyTokens',
                request_serializer=tourism_dot_payment_dot_v1_dot_payment__pb2.ListMyTokensRequest.SerializeToString,
                response_deserializer=tourism_dot_payment_dot_v1_dot_payment__pb2.ListMyTokensResponse.FromString,
                _registered_method=True)
        self.HasToken = channel.unary_unary(
                '/tourism.payment.v1.PaymentService/HasToken',
                request_serializer=tourism_dot_payment_dot_v1_dot_payment__pb2.HasTokenRequest.SerializeToString,
                response_deserializer=tourism_dot_payment_dot_v1_dot_payment__pb2.HasTokenResponse.FromString,
                _registered_method=True)


class PaymentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFromCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Checkout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMyTokens(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HasToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCart,
                    request_deserializer=tourism_dot_payment_dot_v1_dot_payment__pb2.GetCartRequest.FromString,
                    response_serializer=tourism_dot_payment_dot_v1_dot_payment__pb2.ShoppingCart.SerializeToString,
            ),
            'AddToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToCart,
                    request_deserializer=tourism_dot_payment_dot_v1_dot_payment__pb2.AddToCartRequest.FromString,
                    response_serializer=tourism_dot_payment_dot_v1_dot_payment__pb2.ShoppingCart.SerializeToString,
            ),
            'RemoveFromCart': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFromCart,
                    request_deserializer=tourism_dot_payment_dot_v1_dot_payment__pb2.RemoveFromCartRequest.FromString,
                    response_serializer=tourism_dot_payment_dot_v1_dot_payment__pb2.ShoppingCart.SerializeToString,
            ),
            'Checkout': grpc.unary_unary_rpc_method_handler(
                    servicer.Checkout,
                    request_deserializer=tourism_dot_payment_dot_v1_dot_payment__pb2.CheckoutRequest.FromString,
                    response_serializer=tourism_dot_payment_dot_v1_dot_payment__pb2.CheckoutResponse.SerializeToString,
            ),
            'ListMyTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMyTokens,
                    request_deserializer=tourism_dot_payment_dot_v1_dot_payment__pb2.ListMyTokensRequest.FromString,
                    response_serializer=tourism_dot_payment_dot_v1_dot_payment__pb2.ListMyTokensResponse.SerializeToString,
            ),
            'HasToken': grpc.unary_unary_rpc_method_handler(
                    servicer.HasToken,
                    request_deserializer=tourism_dot_payment_dot_v1_dot_payment__pb2.HasTokenRequest.FromString,
                    response_serializer=tourism_dot_payment_dot_v1_dot_payment__pb2.HasTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tourism.payment.v1.PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tourism.payment.v1.PaymentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.payment.v1.PaymentService/GetCart',
            tourism_dot_payment_dot_v1_dot_payment__pb2.GetCartRequest.SerializeToString,
            tourism_dot_payment_dot_v1_dot_payment__pb2.ShoppingCart.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.payment.v1.PaymentService/AddToCart',
            tourism_dot_payment_dot_v1_dot_payment__pb2.AddToCartRequest.SerializeToString,
            tourism_dot_payment_dot_v1_dot_payment__pb2.ShoppingCart.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveFromCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.payment.v1.PaymentService/RemoveFromCart',
            tourism_dot_payment_dot_v1_dot_payment__pb2.RemoveFromCartRequest.SerializeToString,
            tourism_dot_payment_dot_v1_dot_payment__pb2.ShoppingCart.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Checkout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.payment.v1.PaymentService/Checkout',
            tourism_dot_payment_dot_v1_dot_payment__pb2.CheckoutRequest.SerializeToString,
            tourism_dot_payment_dot_v1_dot_payment__pb2.CheckoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMyTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.payment.v1.PaymentService/ListMyTokens',
            tourism_dot_payment_dot_v1_dot_payment__pb2.ListMyTokensRequest.SerializeToString,
            tourism_dot_payment_dot_v1_dot_payment__pb2.ListMyTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HasToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tourism.payment.v1.PaymentService/HasToken',
            tourism_dot_payment_dot_v1_dot_payment__pb2.HasTokenRequest.SerializeToString,
            tourism_dot_payment_dot_v1_dot_payment__pb2.HasTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
