# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tourism/example/v1/example.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'tourism/example/v1/example.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n tourism/example/v1/example.proto\x12\x12tourism.example.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x0e\n\x0c\x43heckRequest\"\'\n\rCheckResponse\x12\x16\n\x06status\x18\x01 \x01(\tR\x06status2u\n\rHealthService\x12\x64\n\x05\x43heck\x12 .tourism.example.v1.CheckRequest\x1a!.tourism.example.v1.CheckResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/healthB\xa5\x01ZLgithub.com/pyroaktiv/soa-tourism/gateway/gen/go/tourism/example/v1;examplev1\x92\x41T\x12*\n\x0bGateway API\x12\x14REST-to-gRPC gateway2\x05\x30.1.0*\x02\x01\x02\x32\x10\x61pplication/json:\x10\x61pplication/jsonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tourism.example.v1.example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZLgithub.com/pyroaktiv/soa-tourism/gateway/gen/go/tourism/example/v1;examplev1\222AT\022*\n\013Gateway API\022\024REST-to-gRPC gateway2\0050.1.0*\002\001\0022\020application/json:\020application/json'
  _globals['_HEALTHSERVICE'].methods_by_name['Check']._loaded_options = None
  _globals['_HEALTHSERVICE'].methods_by_name['Check']._serialized_options = b'\202\323\344\223\002\020\022\016/api/v1/health'
  _globals['_CHECKREQUEST']._serialized_start=134
  _globals['_CHECKREQUEST']._serialized_end=148
  _globals['_CHECKRESPONSE']._serialized_start=150
  _globals['_CHECKRESPONSE']._serialized_end=189
  _globals['_HEALTHSERVICE']._serialized_start=191
  _globals['_HEALTHSERVICE']._serialized_end=308
# @@protoc_insertion_point(module_scope)
