// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               unknown
// source: tourism/stakeholders/v1/stakeholders.proto

/* eslint-disable */

export const protobufPackage = "tourism.stakeholders.v1";

/** Profile holds all public profile fields for a user. */
export interface Profile {
  userId: string;
  name: string;
  surname: string;
  bio: string;
  motto: string;
  /** photo_url is empty when no photo has been uploaded. */
  photoUrl: string;
  username: string;
}

export interface GetProfileRequest {
  userId: string;
}

/**
 * UpdateProfileRequest supports partial updates — only fields that are
 * explicitly set (via proto3 optional) will be written to the database.
 */
export interface UpdateProfileRequest {
  userId: string;
  name?: string | undefined;
  surname?: string | undefined;
  bio?: string | undefined;
  motto?:
    | string
    | undefined;
  /** photo_url should be the full Filer URL returned after a direct upload to SeaweedFS. */
  photoUrl?: string | undefined;
}

export interface DeleteProfilePhotoRequest {
  userId: string;
}
